/**
 * Regenerates the root SKILLS.md index from current skill frontmatter.
 *
 * Run: pnpm index
 *
 * Output: SKILLS.md at repo root.
 */

import { writeFile } from "node:fs/promises";
import { join } from "node:path";
import { listSkillDirs, loadSkill, REPO_ROOT } from "./_lib.ts";

async function main() {
  const skillNames = await listSkillDirs();
  const skills = (await Promise.all(skillNames.map((n) => loadSkill(n).catch(() => null))))
    .filter((s): s is NonNullable<typeof s> => s !== null);

  const lines: string[] = [];
  lines.push("# Skills index");
  lines.push("");
  lines.push("> Auto-generated by `pnpm index`. Do not edit by hand.");
  lines.push("");

  if (skills.length === 0) {
    lines.push("_No skills yet. Add one with `pnpm new <name>`._");
  } else {
    lines.push(`${skills.length} skill${skills.length === 1 ? "" : "s"} in this repo.`);
    lines.push("");
    lines.push("| Skill | Description |");
    lines.push("|---|---|");
    for (const s of skills) {
      const desc = s.frontmatter.description.replace(/\|/g, "\\|").replace(/\n/g, " ");
      lines.push(`| [\`${s.name}\`](skills/${s.name}/) | ${desc} |`);
    }
    lines.push("");
    lines.push("## Categorised");
    lines.push("");
    const byCategory = new Map<string, typeof skills>();
    for (const s of skills) {
      const cat = (s.frontmatter.metadata?.category as string) ?? "uncategorised";
      const arr = byCategory.get(cat) ?? [];
      arr.push(s);
      byCategory.set(cat, arr);
    }
    for (const [cat, list] of [...byCategory.entries()].sort()) {
      lines.push(`### ${cat}`);
      lines.push("");
      for (const s of list) {
        lines.push(`- [\`${s.name}\`](skills/${s.name}/)`);
      }
      lines.push("");
    }
  }

  const output = lines.join("\n") + "\n";
  const outPath = join(REPO_ROOT, "SKILLS.md");
  await writeFile(outPath, output, "utf8");
  console.log(`Wrote ${outPath} (${skills.length} skill${skills.length === 1 ? "" : "s"})`);
  return 0;
}

main().then((code) => process.exit(code));
